steps:
- id: 'Build fat jar'
  name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
  dir: 'resourcetech'
- id: "Prepare staging directory"
  name: 'ubuntu'
  args: ['mkdir', 'deploy-build']
  dir: 'resourcetech'
- name: 'ubuntu'
  args: ['cp', 'src/main/appengine/app.yaml', 'deploy-build/']
  dir: 'resourcetech'
- name: 'ubuntu'
  args: ['cp', '/workspace/resourcetech/target/resourcetech-appengine-0.1.0-SNAPSHOT.war', 'deploy-build/']
  dir: 'resourcetech'
- id: "Deploy to AppEngine"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'deploy-build/']
  dir: 'resourcetech'
timeout: '1600s'
